---
- name: Query an Open API
  hosts: localhost
  connection: local

  vars:
      majorcity: 'http://api.citybik.es/v2/networks'

  tasks:
  - name: Send an HTTP GET to API
    ansible.builtin.uri:
      method: GET
      url: "{{ majorcity }}"
    register: data

  - name: Use debug with a loop across the JSON data
    ansible.builtin.debug:
      msg: "On the {{ item.get('company') }} in: {{ item.get('location.city') }}"
    loop: "{{ data.get('json').get('networks') }}"
